spring.application.name=PhotoAppApiConfigServer
server.port=8012

spring.cloud.config.server.git.uri=https://github.com/niranzanmaharana/PhotoAppConfig
spring.cloud.config.server.git.username=niranzanmaharana
spring.cloud.config.server.git.password=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
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=master

management.endpoints.web.exposure.include=busrefresh

#rabbitmq properties
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.template.exchange=response.exchange
spring.rabbitmq.template.routing-key=response.routing.key
spring.rabbitmq.virtual-host=/
