server.port=8011
spring.application.name=zuul
eureka.client.serviceUrl.defaultZone=http://localhost:8010/eureka

spring.config.import=optional:configserver:http://localhost:8012

#To stop the h2-console request forwarding the request to whitable page for first once or twice.

ribbon.ReadTimeout=60000

#rabbitmq properties
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.template.exchange=response.exchange
spring.rabbitmq.template.routing-key=response.routing.key
spring.rabbitmq.virtual-host=/