server.port=8011
spring.application.name=zuul
eureka.client.serviceUrl.defaultZone=http://localhost:8010/eureka

spring.config.import=optional:configserver:http://localhost:8012

#To stop the h2-console request forwarding the request to whitable page for first once or twice.

ribbon.ReadTimeout=60000

#api.h2console.url.path=/users-ws/h2-console/**
#api.registration.url.path=/users-ws/users/
#api.login.url.path=/users-ws/users/login

#authorization.token.header.name=Authorization
#authorization.token.header.prefix=Bearer
#jwt.token.secret.key = niranzan