server.port=${PORT:0}
spring.application.name=users-ws
spring.devtools.restart.enabled=true

eureka.client.serviceUrl.defaultZone=http://localhost:8010/eureka

eureka.instance.prefer-ip-address: true
eureka.instance.instance-id=${spring.application.name}:${instance-id: ${random.value}}
eureka.instance.preferIpAddress=true
eureka.instance.hostname=localhost

spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# API Login url
api.login.url=/user/login

# Permissiable gateway IP address
gateway.ip = 192.168.1.92

#Jwt Token expiration for 10 days
jwt.token.expire.time = 864000000
# Jwt Secret Key
jwt.token.secret.key = niranzan