api.login.url=/users/login
gateway.ip = 192.168.1.92
jwt.token.expire.time = 86400000
jwt.token.secret.key = niranzan

authorization.token.header.name=Authorization
authorization.token.header.prefix=Bearer

api.h2console.url.path=/users-ws/h2-console/**
api.registration.url.path=/users-ws/users/
api.login.url.path=/users-ws/users/login