#api-gateway
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
spring:
  application:
    name: api-gateway # this microservice will be registered with eureka with this name
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # enables automatic routing with api gateway
          lower-case-service-id: true # allows only lower case service name registered with discovery service
