#discover-service
spring:
  application:
    name: discovery-service

server:
  port: 8010

eureka:
  server:
    maxThreadsForPeerReplication: 0
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka