#discover-service
server:
  port: 8010
spring:
  application:
    name: discovery-service

eureka:
  server:
    maxThreadsForPeerReplication: 0
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka