server:
  port: 0
spring:
  application:
    name: user-service
  devtools:
    restart:
      enabled: true
eureka:
  instance:
    hostname: localhost
    instance-id: '${spring.application.name}:${instance-id: ${random.value}}'
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
