server:
  port: '${PORT:0}'
spring:
  application:
    name: user-service # this microservice will be registered with eureka with this name
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  instance:
    hostname: localhost
    instance-id: '${spring.application.name}:${instance-id: ${random.value}}'
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
jwt:
  secret: f8fe67fe-8086-4511-87bb-3be3fe138f3e-f8fe67fe-8086-4511-87bb-3be3fe138f3e
  expiration: 3600
jwtSecret: f8fe67fe-8086-4511-87bb-3be3fe138f3e-f8fe67fe-8086-4511-87bb-3be3fe138f3e
jwtExpiration: 3600
login:
  url: /users/login