server:
  port: 0
spring:
  application:
    name: account-service
  devtools:
    restart:
      enabled: true
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
